/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ImageSlider: typeof import('./components/ImageSlider/index.vue')['default']
    MarkdownPreview: typeof import('./components/MarkdownPreview/index.vue')['default']
    ParticlesClock: typeof import('./components/ParticlesClock/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
