/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./components/Tinymce/index copy 2.vue')['default']
    copy: typeof import('./components/Tinymce/index copy.vue')['default']
    DigitalHuman: typeof import('./components/DigitalHuman/index.vue')['default']
    HtmlRunner: typeof import('./components/HtmlRunner/index.vue')['default']
    ImageSlider: typeof import('./components/ImageSlider/index.vue')['default']
    'Index copy': typeof import('./components/Tinymce/index copy.vue')['default']
    'Index copy 2': typeof import('./components/Tinymce/index copy 2.vue')['default']
    MarkdownPreview: typeof import('./components/MarkdownPreview/index.vue')['default']
    MarkdownWithECharts: typeof import('./components/MarkdownWithECharts/index.vue')['default']
    NavBar: typeof import('./components/NavBar/index.vue')['default']
    ParticlesClock: typeof import('./components/ParticlesClock/index.vue')['default']
    ProcessCards: typeof import('./components/ProcessCards/index.vue')['default']
    'ProcessCards实现文档': typeof import('./components/ProcessCards/ProcessCards实现文档.md')['default']
    README: typeof import('./components/ProcessCards/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tinymce: typeof import('./components/Tinymce/index.vue')['default']
    WpsEditor: typeof import('./components/WpsEditor/index.vue')['default']
  }
}
